# этот скрипт написан по официальному руководтву Action Runner Controller
# https://actions-runner-controller.github.io/actions-runner-controller/

- name: Copy manifest of cert-manager.yaml
  copy:
    src: cert-manager.yaml
    dest: /tmp/cert-manager.yaml

- name: Installing certmanger
  environment:
    KUBECONFIG: ../k8s-cluster_kubeconfig.yaml
  shell: kubectl apply -f \
    /tmp/{{ item }}
  with_items:
    - cert-manager.yaml

- name: Add helm repo
  shell: >
    helm repo add actions-runner-controller https://actions-runner-controller.github.io/actions-runner-controller

- name: Install helm
  environment:
    KUBECONFIG: ../k8s-cluster_kubeconfig.yaml
  ignore_errors: True
  shell: helm upgrade --install --namespace actions-runner-system --create-namespace \
          --set=authSecret.create=true \
          --set=authSecret.github_token="{{github_authtoken}}" \
          --wait actions-runner-controller actions-runner-controller/actions-runner-controller

- name: Render needed object
  template:
    src: runnerdeployment.yaml.j2
    dest: /tmp/runnerdeployment.yaml

- name: Copy manifest of service-account.yaml
  copy:
    src: service_account.yaml
    dest: /tmp/service_account.yaml

- name: Copy manifest of regru-webhook.yaml
  copy:
    src: regru-webhook.yaml
    dest: /tmp/regru-webhook.yaml

- name: Render regru secret
  template:
    src: regru-secret.yaml.j2
    dest: /tmp/regru-secret.yaml

- name: Copy manifest of ClusterIssuerRegru.yaml
  copy:
    src: ClusterIssuerRegru.yaml
    dest: /tmp/ClusterIssuerRegru.yaml


- name: Add needed object
  environment:
    KUBECONFIG: ../k8s-cluster_kubeconfig.yaml
  shell: kubectl apply -f \
           /tmp/{{ item }}
  with_items:
    - regru-secret.yaml
    - regru-webhook.yaml
    - service_account.yaml
    - runnerdeployment.yaml
    - ClusterIssuerRegru.yaml

