# больше информации про эту возможность
# https://github.com/kubernetes/cloud-provider-openstack/blob/master/docs/openstack-cloud-controller-manager/expose-applications-using-loadbalancer-type-service.md
- name: Add helm repo
  shell: >
    helm repo add ingress-nginx https://kubernetes.github.io/ingress-nginx

- name: Install helm chart
  environment:
    KUBECONFIG: ../k8s-cluster_kubeconfig.yaml
  shell: helm upgrade --install ingress-nginx ingress-nginx \
          --repo https://kubernetes.github.io/ingress-nginx \
          --namespace ingress-nginx --create-namespace \
          --set controller.config.use-proxy-protocol="true" \
          --set controller.config.enable-real-ip="true" \
          --set 'controller.service.annotations.loadbalancer\.openstack\.org/proxy-protocol=true' \
          --set controller.service.externalTrafficPolicy="Local" \
          --set controller.replicaCount=2

 # Cоздание loadbalancer в кластере, который создаст
 # объект в vkcould, который будет пускать входящий трафик
 # по протоколу http          
#- name: Copy manifest of loadbalancer.yml
#  copy:
#    src: loadbalancer.yml
#    dest: /tmp/loadbalancer.yml
#
#- name: Add needed object
#  environment:
#    KUBECONFIG: ../k8s-cluster_kubeconfig.yaml
#  shell: kubectl apply -f \
#           /tmp/loadbalancer.yml
