---
# tasks file for .

- name: "Installing runner"
  import_tasks: ci.yml

- name: "Installing ingress"
  import_tasks: ingress.yml

- name: "Installing demo-boutique"
  import_tasks: ci-demo-boutique.yml